/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sources;

import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author sijitend
 */
public class GirviDeposits extends javax.swing.JFrame {
    private UpdateTrackingTableModel tableModel_deposits;
    public String sIndexForDeposits;
    public static boolean bGirviDeposits = false;
     public static MyMain iClass;
     public static boolean bGirviON = true;
    /**
     * Creates new form GirviDeposits
     */
    public GirviDeposits(String sIndex) {
        bGirviON = false;
        sIndexForDeposits = sIndex;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Vector[] dbdata =  MyMain.jj("GIRVI_DEPOSITS"+sIndexForDeposits);
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jButtonAdd_GIRVI_DEPOSIT = new javax.swing.JButton();
        jButton_UPDATE_GIRVI_DEPOSIT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableModel_deposits  = new UpdateTrackingTableModel(0, new String [] {
            "Date", "Amount", "Involved Person"
        });
        jXTable1.setModel(tableModel_deposits);
        jScrollPane1.setViewportView(jXTable1);
        jXTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jXTable1.setGridColor(new java.awt.Color(0, 204, 0));
        jXTable1.getTableHeader().setDefaultRenderer(new SimpleHeaderRenderer());
        jXTable1.setShowGrid(true);

        String[]saEntries = dbdata[0].toString().replaceAll("[\\[\\]]", "").trim().replaceAll("^\\,","").split(",");
        //tableModel_deposits.setRowCount(saEntries.length);

        for(int i=0; i<saEntries.length; i++)
        {
            String[]saVal = saEntries[i].split(":");
            tableModel_deposits.addRow(saVal);
        }

        jButtonAdd_GIRVI_DEPOSIT.setText("  ADD  ");
        jButtonAdd_GIRVI_DEPOSIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdd_GIRVI_DEPOSITActionPerformed(evt);
            }
        });

        jButton_UPDATE_GIRVI_DEPOSIT.setText("  UPDATE  ");
        jButton_UPDATE_GIRVI_DEPOSIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UPDATE_GIRVI_DEPOSITActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\ook.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonAdd_GIRVI_DEPOSIT)
                        .addGap(39, 39, 39)
                        .addComponent(jButton_UPDATE_GIRVI_DEPOSIT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd_GIRVI_DEPOSIT)
                    .addComponent(jButton_UPDATE_GIRVI_DEPOSIT))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdd_GIRVI_DEPOSITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdd_GIRVI_DEPOSITActionPerformed
        // TODO add your handling code here:
        bGirviDeposits = true;
        tableModel_deposits.addRow(new Object[]{
        "", "", ""
    });
       
        
    }//GEN-LAST:event_jButtonAdd_GIRVI_DEPOSITActionPerformed

    private void jButton_UPDATE_GIRVI_DEPOSITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UPDATE_GIRVI_DEPOSITActionPerformed
       
        System.out.println("updateeee");
        int[] updatedIndexes = tableModel_deposits.getUpdatedRowIndexes();
        if (updatedIndexes.length > 0) 
        {
            int iRet = JOptionPane.showConfirmDialog(this, "<html><b>modification Detected</b><br><br>Want to update ?</html>", "Stock Update", JOptionPane.INFORMATION_MESSAGE);
            if (iRet == 0) {

                for (int a = 0; a < updatedIndexes.length; a++) 
                {
                    int idx = updatedIndexes[a];
                        String date = tableModel_deposits.getValueAt(idx, 0).toString();
                        String amount = tableModel_deposits.getValueAt(idx, 1).toString();
                        String inv_person = tableModel_deposits.getValueAt(idx, 2).toString();
                        String sDeposits = ","+date+":"+amount+":"+inv_person;
                        System.out.println("jButton_UPDATE_GIRVI_DEPOSITActionPerformed :"+sDeposits );
                  
                        String sq =  "UPDATE loan SET `deposits`= concat(`deposits`,'"+sDeposits+"') WHERE `INDEX`= '"+sIndexForDeposits+"' ";
                        SqlQuery qe = new SqlQuery();
                        System.out.println(qe.InsertData(sq));
                   
                }
            }
        }
        else
            JOptionPane.showMessageDialog(this, "<html><b>None of the values are updated</b></html>", "Update", JOptionPane.WARNING_MESSAGE);

                        //ee = "UPDATE loan SET `item`=" + "'" + values[1] + "', " + "`dol`= " + sDol + " , " + "`Total_Amount`=" + "'" + values[3] + "' , " + "`pAmount`=" + "'" + values[4] + "'" + ", `weight`=" + "'" + values[6] + "'" + " , " + "`interest`=" + "'" + values[5] + "'" + "  WHERE UserID=" + "'" + sUserID + "'" + " and `index` = " + "'" + values[0] + "'";

    }//GEN-LAST:event_jButton_UPDATE_GIRVI_DEPOSITActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton_UPDATE_GIRVI_DEPOSIT.doClick();
        iClass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         iClass.setVisible(true);
         bGirviON = true;
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirviDeposits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirviDeposits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirviDeposits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirviDeposits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirviDeposits("1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd_GIRVI_DEPOSIT;
    private javax.swing.JButton jButton_UPDATE_GIRVI_DEPOSIT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
