package sources;


import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.SplashScreen;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.String;
import java.util.Enumeration;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sijitend
 */
public class NewJFrame extends javax.swing.JFrame {

    public static String DEBT_REMINDER_FROM_CONFIG, MORTGAGE_REMINDER_FROM_CONFIG;
    public static String TIME_FOR_ALL_REMINDER_FROM_CONFIG,SET_TODAY_GOLD_RATE=null, SET_TODAY_SILVER_RATE= null;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame(){
        try{
        initComponents();
        Container c = this.getContentPane();
        
        jXLoginPane1.setBannerText("Admin Login");
        c.setBackground(Color.WHITE);
        BufferedImage img = ImageIO.read(new File("C:\\Users\\sijitend\\Pictures\\pola.jpg"));
      //  this.setIconImage(img);
       // this.getContentPane().set  setBanner(img);
        }catch(IOException e)
        {
            System.out.println("===========>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The co/ntent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        jButton1 = new javax.swing.JButton();
        jXLoginPane1 = new org.jdesktop.swingx.JXLoginPane();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Window");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(500, 320));
        setName("Admin Login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 800));
        setShape(new Ellipse2D.Double(0,0,650,650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sijitend\\Pictures\\jewellarey_icons\\5.jpg")); // NOI18N
        jButton1.setFocusCycleRoot(true);
        jButton1.setIconTextGap(0);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 140, 50));

        jXLoginPane1.setBackground(new java.awt.Color(0, 204, 204));
        jXLoginPane1.setForeground(new java.awt.Color(255, 0, 102));
        jXLoginPane1.setFocusCycleRoot(true);
        jXLoginPane1.setMessage("Enter Username and Password !");
        jXLoginPane1.setName("jitu"); // NOI18N
        jXLoginPane1.setNextFocusableComponent(jButton1);
        getContentPane().add(jXLoginPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 400, -1));

        jXLabel1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\loogin.png")); // NOI18N
        getContentPane().add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 550, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sijitend\\Pictures\\jewellarey_icons\\7.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 120, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sijitend\\Pictures\\jewellarey_icons\\7.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jXLoginPane1.getUserName().length() == 0  || jXLoginPane1.getPassword().length ==0)
        {
            JOptionPane.showMessageDialog(NewJFrame.this, "Please Enter Username/Password", "Login", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            System.out.println("==>"+jXLoginPane1.getUserName()+String.valueOf(jXLoginPane1.getPassword()));
            if(String.valueOf(jXLoginPane1.getPassword()).equalsIgnoreCase("demo"))
            {
               System.out.println("OK");
                    this.setVisible(false);
                try {
                    loadconfig();
                   // (new Thread(new HelloRunnable())).start();
                    new MyMain().setVisible(true);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                
                JOptionPane.showMessageDialog(NewJFrame.this, "<html><b>Couldn't log in</b><br><br>Check your user name and password ! </html>", "Login", JOptionPane.ERROR_MESSAGE);
                jXLoginPane1.setPassword(new char[0]);
                //this.dispose();
            }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new NewJFrame().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLoginPane jXLoginPane1;
    // End of variables declaration//GEN-END:variables

    private void loadconfig() throws FileNotFoundException {
        
        Properties prop = new Properties();
	InputStream input = null;

 	try {

		String filename = "config.properties";
		input = getClass().getClassLoader().getResourceAsStream(filename);
		if (input == null) {
			System.out.println("Sorry, unable to find " + filename);
			return;
		}

		prop.load(input);
                MORTGAGE_REMINDER_FROM_CONFIG = prop.getProperty("NORMAL_MORTGAGE_REMINDER_IN_MONTHS");
		DEBT_REMINDER_FROM_CONFIG = prop.getProperty("NORMAL_DEBT_REMINDER_IN_MONTHS");
                TIME_FOR_ALL_REMINDER_FROM_CONFIG = " "+prop.getProperty("TIME_FOR_ALL_REMINDER");
               // SET_TODAY_GOLD_RATE = 
                Vector[] dbdata =   MyMain.jj("TODAY_RATE");
                int j = 0;
                System.out.println("--Rates---");
                System.out.println(dbdata[0]);
                if(dbdata[0].size() != 0)
                {
                    SET_TODAY_GOLD_RATE = dbdata[0].get(0).toString().split(",")[1];
                    SET_TODAY_SILVER_RATE = dbdata[0].get(0).toString().split(",")[2].replaceAll("\\]", "");
                    
                }
                
                Enumeration<?> e = prop.propertyNames();
		while (e.hasMoreElements()) {
			String key = (String) e.nextElement();
			String value = prop.getProperty(key);
			System.out.println("Key : " + key + ", Value : " + value);
		}

	} catch (IOException ex) {
		ex.printStackTrace();
	} finally {
		if (input != null) {
			try {
				input.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
    
    }
}


//class HelloRunnable implements Runnable {
//    
//private static volatile boolean isRunning = true;
//
//    public void run() 
//    {
//         while (isRunning){
//        System.out.println("Hello from a thread!");
//        SplashScreen splash = SplashScreen.getSplashScreen();
//        Graphics2D g = (Graphics2D) splash.createGraphics();
//        Dimension dim = splash.getSize();
//        splash.update();
//         }
//    }
//     public static void kill() {
//         System.out.println("Killed..............");
//       isRunning = false;
//   }
//}