package sources;


import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sijitend
 */
public  class NewJFrame71 extends javax.swing.JFrame {

    static String UserID;
    public static MyMain iClass;
    public static String getFirst_Name() {
        return First_Name;
    }

    public static void setFirst_Name(String First_Name) {
        NewJFrame3.First_Name = First_Name;
    }

    public static String getLast_Name() {
        return Last_Name;
    }

    public static void setLast_Name(String Last_Name) {
        NewJFrame3.Last_Name = Last_Name;
    }

    public static String getFatherName() {
        return FatherName;
    }

    public static void setFatherName(String FatherName) {
        NewJFrame3.FatherName = FatherName;
    }

    public static String getMobile() {
        return Mobile;
    }

    public static void setMobile(String Mobile) {
        NewJFrame3.Mobile = Mobile;
    }

    public static String getVill() {
        return Vill;
    }

    public static void setVill(String Vill) {
        NewJFrame3.Vill = Vill;
    }

  

    public static void setTown(String Town) {
        NewJFrame3.Town = Town;
    }


    public static void setDist(String Dist) {
        NewJFrame3.Dist = Dist;
    }


    public static void setLandmark(String Landmark) {
        NewJFrame3.Landmark = Landmark;
    }

    public static void setPINCODE(int PINCODE) {
        NewJFrame3.PINCODE = PINCODE;
    }

    public static String getAddress() {
        return Address;
    }

    public static void setAddress(String Address) {
        NewJFrame3.Address = Address;
    }

   
    public static void setCountry(String Country) {
        NewJFrame3.Country = Country;
    }

    public String getUserID() {
        return UserID;
    }


    static String First_Name, Salary;

    static String Last_Name;
    static String FatherName;
    static String Mobile;
    static String Vill;
    static String Address;
    static String Date_of_Joining;
    static String Last_Day="";
    static String Final_Payment="NA";
    static String ExEmployee="No";
    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame71() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_f_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_L_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Father_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Vill_Name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Add_Name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser_Date_of_Joining = new com.toedter.calendar.JDateChooser();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jTextField_Sal_Name = new org.jdesktop.swingx.JXTextField();
        jTextField__emp_Mob_Name = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                myclose(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\fnmae~1.png")); // NOI18N
        jLabel1.setText("First Name :");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jTextField_f_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_f_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_f_NameFocusLost(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\lname~1.png")); // NOI18N
        jLabel2.setText("Last Name :");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);

        jTextField_L_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_L_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_L_NameFocusLost(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\fathe~1.png")); // NOI18N
        jLabel3.setText("Father's Name :");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);

        jTextField_Father_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Father_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Father_NameFocusLost(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\mob~1.png")); // NOI18N
        jLabel4.setText("Mobile :");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);

        jTextField_Vill_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_Vill_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Vill_NameFocusLost(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\vilg.png")); // NOI18N
        jLabel9.setText("Address :");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);

        jTextField_Add_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\villeg.png")); // NOI18N
        jLabel13.setText("Village :");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\ook.png")); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser_Date_of_Joining.setDateFormatString("yyyy.MM.dd");
        jDateChooser_Date_of_Joining.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDateChooser_Date_of_Joining.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_Date_of_JoiningPropertyChange(evt);
            }
        });

        jXLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jXLabel1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\dateofjoin.png")); // NOI18N
        jXLabel1.setText("Date of Joining");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXLabel1.setOpaque(true);

        jXLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jXLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jXLabel2.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\emp.png")); // NOI18N
        jXLabel2.setText("       Employee Details");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXLabel2.setOpaque(true);

        jXLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jXLabel3.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\salary.png")); // NOI18N
        jXLabel3.setText("Salary :");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jXLabel3.setOpaque(true);

        jTextField_Sal_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Sal_NameFocusLost(evt);
            }
        });

        jTextField__emp_Mob_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField__emp_Mob_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField__emp_Mob_NameFocusLost(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\ccccl.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser_Date_of_Joining, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField__emp_Mob_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Father_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_L_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_f_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Vill_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Add_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Sal_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_f_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_L_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Father_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField__emp_Mob_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Vill_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Add_Name)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Sal_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_Date_of_Joining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        First_Name = jTextField_f_Name.getText();

        Last_Name = jTextField_L_Name.getText();
        FatherName = jTextField_Father_Name.getText();
        Mobile = jTextField_Vill_Name.getText();
     
        Vill = jTextField_Vill_Name.getText();
        Address = jTextField_Add_Name.getText();
        Salary = jTextField__emp_Mob_Name.getText();
       
        String ret;
        String[] sa = new String[9];
        if( !First_Name.isEmpty() && !Last_Name.isEmpty()  && !FatherName.isEmpty()  && !Mobile.isEmpty()  &&  !Vill.isEmpty()  && !Address.isEmpty()  && !Salary.isEmpty()  && !Date_of_Joining.isEmpty()  && !ExEmployee.isEmpty() )
        {
            ret = SetVal();
            if(ret.equalsIgnoreCase("Success"))
            {
                    System.out.println(ret);
                    JOptionPane.showMessageDialog(this.getComponent(0), ret);
                    DefaultTableModel Dt = (DefaultTableModel)MyMain.jXTable6.getModel();
                    sa[0] = First_Name;
                    sa[1] = Last_Name;
                    sa[2] = FatherName;
                    sa[3] = Mobile;
                    sa[4] = Vill;
                    sa[5] = Address;
                    sa[6] = Salary;
                    sa[7] = Date_of_Joining;
                    sa[8] = ExEmployee;
                    Dt.addRow(sa);
                    iClass.setVisible(true);
                    this.dispose();
            }
            else
                    JOptionPane.showMessageDialog(this.getComponent(0), "Database Error","" ,JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this.getComponent(0), "No Data","" ,JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser_Date_of_JoiningPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_Date_of_JoiningPropertyChange
        // TODO add your handling code here:

        JDateChooser dateChooser = new JDateChooser();

        if ("date".equals(evt.getPropertyName())) {
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MMM-yyyy");
            Date_of_Joining = dformat.format(((Date) evt.getNewValue()));
            System.out.println(evt.getPropertyName() + ": " + Date_of_Joining);
        }
    }//GEN-LAST:event_jDateChooser_Date_of_JoiningPropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        iClass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void myclose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_myclose
        // TODO add your handling code here:
        iClass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myclose

    private void jTextField__emp_Mob_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField__emp_Mob_NameFocusLost
         if(!jTextField__emp_Mob_Name.getText().isEmpty() &&  !jTextField__emp_Mob_Name.getText().matches("^\\d+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Mobile Number", "Invalid Mobile", JOptionPane.WARNING_MESSAGE);
            jTextField__emp_Mob_Name.setText("");
            jTextField__emp_Mob_Name.requestFocusInWindow();
            
        }
    }//GEN-LAST:event_jTextField__emp_Mob_NameFocusLost

    private void jTextField_f_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_f_NameFocusLost
           if(!jTextField_f_Name.getText().isEmpty() &&  !jTextField_f_Name.getText().matches("^([a-zA-Z]{3,30}\\s*)+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect First Name", "Invalid Name", JOptionPane.WARNING_MESSAGE);
            jTextField_f_Name.setText("");
            jTextField_f_Name.requestFocusInWindow();
            
        }else
           jTextField_f_Name.setText(jTextField_f_Name.getText().toUpperCase());
    }//GEN-LAST:event_jTextField_f_NameFocusLost

    private void jTextField_L_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_L_NameFocusLost
        if(!jTextField_L_Name.getText().isEmpty() &&  !jTextField_L_Name.getText().matches("^([a-zA-Z]{3,30}\\s*)+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Last Name", "Invalid Name", JOptionPane.WARNING_MESSAGE);
            jTextField_L_Name.setText("");
            jTextField_L_Name.requestFocusInWindow();
            
        }else
           jTextField_L_Name.setText(jTextField_L_Name.getText().toUpperCase());
    }//GEN-LAST:event_jTextField_L_NameFocusLost

    private void jTextField_Father_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Father_NameFocusLost
         if(!jTextField_Father_Name.getText().isEmpty() &&  !jTextField_Father_Name.getText().matches("^([a-zA-Z]{3,30}\\s*)+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Father Name", "Invalid Name", JOptionPane.WARNING_MESSAGE);
            jTextField_Father_Name.setText("");
            jTextField_Father_Name.requestFocusInWindow();
            
        }else
           jTextField_Father_Name.setText(jTextField_Father_Name.getText().toUpperCase());
    }//GEN-LAST:event_jTextField_Father_NameFocusLost

    private void jTextField_Vill_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Vill_NameFocusLost
        
         if(!jTextField_Vill_Name.getText().isEmpty() &&  !jTextField_Vill_Name.getText().matches("^([a-zA-Z]{3,30}\\s*)+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Father Name", "Invalid Name", JOptionPane.WARNING_MESSAGE);
            jTextField_Vill_Name.setText("");
            jTextField_Vill_Name.requestFocusInWindow();
            
        }else
           jTextField_Vill_Name.setText(jTextField_Vill_Name.getText().toUpperCase());
    }//GEN-LAST:event_jTextField_Vill_NameFocusLost

    private void jTextField_Sal_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Sal_NameFocusLost
        if(!jTextField_Sal_Name.getText().isEmpty() &&  !jTextField_Sal_Name.getText().matches("^\\d+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect Mobile Number", "Invalid Mobile", JOptionPane.WARNING_MESSAGE);
            jTextField_Sal_Name.setText("");
            jTextField_Sal_Name.requestFocusInWindow();
            
        }    }//GEN-LAST:event_jTextField_Sal_NameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser_Date_of_Joining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_Add_Name;
    private javax.swing.JTextField jTextField_Father_Name;
    private javax.swing.JTextField jTextField_L_Name;
    private org.jdesktop.swingx.JXTextField jTextField_Sal_Name;
    private javax.swing.JTextField jTextField_Vill_Name;
    private javax.swing.JTextField jTextField__emp_Mob_Name;
    private javax.swing.JTextField jTextField_f_Name;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    // End of variables declaration//GEN-END:variables
public String toMyString() {
        StringBuilder result = new StringBuilder();
        String newLine = System.getProperty("line.separator");

        result.append(this.getClass().getName());
        result.append(" Object {");
        result.append(newLine);

        //determine fields declared in this class only (no fields of superclass)
        Field[] fields = this.getClass().getDeclaredFields();

        //print field names paired with their values
        for (Field field : fields) {
            result.append("  ");
            try {
                result.append(field.getName());
                result.append(": ");
                //requires access to private field:
                result.append(field.get(this));
            } catch (IllegalAccessException ex) {
                System.out.println(ex);
            }
            result.append(newLine);
        }
        result.append("}");

        return result.toString();
    } 

    public static String SetVal() {

        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://127.0.0.1:3306/work", "root", "root");

            Statement stmt = con.createStatement();
              String sDoj = "STR_TO_DATE("+"'"+Date_of_Joining+"'"+",\'%d-%M-%Y\')";
            String tmp = "INSERT INTO employee (`First_Name`, `Last_Name`, `FatherName`, `Mobile`, `Vill`,`Address`,`Salary` ,`Date_Of_Joining`,`ex_emp`,`final_payment`) "
                    + "VALUES (" + "'" + First_Name + "'" + "," + "'" + Last_Name + "'" + "," + "'" + FatherName + "'" + "," + "'" + Mobile + "'" + "," + "'" + Vill + "'" + "," 
                    + "'" + Address + "'"+" , "+"'"+Salary+"'"+" ,"+sDoj+ " , "+ "'"+ExEmployee+"'"+", "+"'"+Final_Payment+"'"+" );";

            System.out.println("==>" + tmp);
                String ret="Failed";
            if( 0< stmt.executeUpdate(tmp))
            {
                    ret = "Success";
            }
            
            con.close();
            return  ret;

        } catch (Exception e) {
            System.out.println(e);
            return "Failed";
        }
    }


   public    void validateInput(JTextField jt, String pattern)
  {
//    Pattern r = Pattern.compile(pattern);
//    Matcher m = r.matcher(jt.getText());
//    if (!m.matches())
//    {
//      JOptionPane.showMessageDialog(NewJFrame71.this,"Error", "Validation", JOptionPane.WARNING_MESSAGE);
//      jt.setText("");
//    }
//    
      System.out.println("");
  }

}
