package sources;



import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sijitend
 */
public class SetReminderForMortAndDebt extends javax.swing.JFrame {
    private String sReminder_Days;
    private String sReminder_Years;
    private String sReminder_Months;
    private String Custom_remend_Date;
    public static MyMain iClass;
    public String remend_opt=null;
    private String expDateString;
    /**
     * Creates new form NewJFrame74
     */
    public SetReminderForMortAndDebt(String opt) {
        remend_opt = opt;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_Custom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jButton2 = new javax.swing.JButton();
        jDatechoose_Cuest_rem_date = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel_OR = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                myclose(evt);
            }
        });

        jTextField_Custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CustomActionPerformed(evt);
            }
        });
        jTextField_Custom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_CustomFocusLost(evt);
            }
        });
        jTextField_Custom.getDocument().addDocumentListener(new DocumentListener()
            {
                @Override
                public void removeUpdate(DocumentEvent e)
                {

                }

                @Override
                public void insertUpdate(DocumentEvent e)
                {
                    validateInput(jTextField_Custom.getText(),"\\d+");
                }

                @Override
                public void changedUpdate(DocumentEvent e) {}
                // Not needed for plain-text fields
            });

            jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jButton1.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\ook.png")); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jXLabel2.setBackground(new java.awt.Color(255, 255, 255));
            jXLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jXLabel2.setForeground(new java.awt.Color(0, 0, 255));
            jXLabel2.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\GHANTA~2.png")); // NOI18N
            jXLabel2.setText("       Custom Reminder");
            jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jXLabel2.setOpaque(true);

            jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jButton2.setIcon(new javax.swing.ImageIcon("C:\\dist\\img\\ccccl.png")); // NOI18N
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jDatechoose_Cuest_rem_date.setDateFormatString("yyyy.MM.dd");
            jDatechoose_Cuest_rem_date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    jDatechoose_Cuest_rem_datePropertyChange(evt);
                }
            });
            jDatechoose_Cuest_rem_date.setEnabled(false);

            jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jCheckBox1.setText("Soecific Date :");
            jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jCheckBox1ItemStateChanged(evt);
                }
            });

            jLabel_OR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel_OR.setText(" OR ");

            jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Days", "Months", "Years" }));
            jComboBox4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox4ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(jLabel_OR))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox1)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDatechoose_Cuest_rem_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jTextField_Custom)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(25, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Custom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                    .addComponent(jLabel_OR)
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDatechoose_Cuest_rem_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CustomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CustomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if (jCheckBox1.isSelected())
       {
         if(Custom_remend_Date.isEmpty())  
         {
             JOptionPane.showMessageDialog(SetReminderForMortAndDebt.this, "Select the date !", "No Data", JOptionPane.WARNING_MESSAGE);
         }
       }
       else
        if(!jTextField_Custom.getText().isEmpty())
        {
            SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yyyy");
            Calendar cal = Calendar.getInstance();
            cal.setTime(new Date());
        
            if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("Days"))
            {
                sReminder_Days = jTextField_Custom.getText();
                cal.add(Calendar.DATE, Integer.parseInt(sReminder_Days));
                expDateString = sd.format(cal.getTime());
            }
            else if(jComboBox4.getSelectedItem().toString().equalsIgnoreCase("Months"))
            {
                sReminder_Months = jTextField_Custom.getText();
                cal.add(Calendar.DATE, Integer.parseInt(sReminder_Months)*30);
                expDateString = sd.format(cal.getTime());
            }
            else
            {
                sReminder_Years = jTextField_Custom.getText();
                cal.add(Calendar.DATE, Integer.parseInt(sReminder_Months)*365);
                expDateString = sd.format(cal.getTime());
            }
            if(remend_opt.equalsIgnoreCase("debt"))
            {
                MyMain.sSet_Reminder_for_Debt_str = expDateString+" "+NewJFrame.TIME_FOR_ALL_REMINDER_FROM_CONFIG;
                System.out.println("MyMain.sSet_Reminder_for_Debt_str : "+MyMain.sSet_Reminder_for_Debt_str);
                MyMain.jRadioButton_remend_debt_norm.setSelected(false);
                MyMain.jRadioButton_remend_debt_cust.setSelected(true);

            }
            else
            {
                MyMain.sSet_Reminder_for_Mortgage = expDateString+" "+NewJFrame.TIME_FOR_ALL_REMINDER_FROM_CONFIG;
                System.out.println("MyMain.sSet_Reminder_for_Mortgage : "+MyMain.sSet_Reminder_for_Mortgage);
                MyMain.jRadioButton_remend_mort_norm.setSelected(false);
                MyMain.jRadioButton_remend_mort_cust.setSelected(true);

            }
            
            JOptionPane.showMessageDialog(SetReminderForMortAndDebt.this, "Custom Reminder setup successfully ! ", "Custom Reminder", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        }
        else
        {
            JOptionPane.showMessageDialog(SetReminderForMortAndDebt.this, "First Enter Details :", "No Data", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        MyMain.jRadioButton_remend_debt_norm.setSelected(true);
        MyMain.jRadioButton_remend_debt_cust.setSelected(false);
        iClass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDatechoose_Cuest_rem_datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatechoose_Cuest_rem_datePropertyChange
        // TODO add your handling code here:

      //  JDateChooser dateChooser = new JDateChooser();

        if ("date".equals(evt.getPropertyName())) {
            SimpleDateFormat dformat = new SimpleDateFormat("dd-MMM-yyyy");
            Custom_remend_Date = dformat.format(((Date) evt.getNewValue()));
            System.out.println(evt.getPropertyName() + ": " + Custom_remend_Date);
            
            if(remend_opt.equalsIgnoreCase("debt"))
            {
                MyMain.sSet_Reminder_for_Debt_str = Custom_remend_Date+" "+NewJFrame.TIME_FOR_ALL_REMINDER_FROM_CONFIG;
            }
            else
            {
                MyMain.sSet_Reminder_for_Mortgage = Custom_remend_Date+" "+NewJFrame.TIME_FOR_ALL_REMINDER_FROM_CONFIG;
            }
        }
    }//GEN-LAST:event_jDatechoose_Cuest_rem_datePropertyChange

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED)
         {
             jDatechoose_Cuest_rem_date.setEnabled(true);
             jTextField_Custom.setText("");
             
         }
         else
         {
             jDatechoose_Cuest_rem_date.setEnabled(false);
             jTextField_Custom.setEnabled(true);
             
         }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void myclose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_myclose
        // TODO add your handling code here:
        if(remend_opt == null)
        {
            System.out.println("INCLOSE");
            MyMain.jRadioButton_remend_debt_norm.setSelected(true);
            MyMain.jRadioButton_remend_debt_cust.setSelected(false);
        }
        else
            remend_opt = null;
        
        iClass.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myclose

    private void jTextField_CustomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_CustomFocusLost
        if(!jTextField_Custom.getText().isEmpty() &&  !jTextField_Custom.getText().matches("^\\d+$"))
        {
            JOptionPane.showMessageDialog(this, "Incorrect value for reminder", "Invalid Data", JOptionPane.WARNING_MESSAGE);
            jTextField_Custom.setText("");
            jTextField_Custom.requestFocusInWindow();
            
        }
    }//GEN-LAST:event_jTextField_CustomFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox4;
    private com.toedter.calendar.JDateChooser jDatechoose_Cuest_rem_date;
    private javax.swing.JLabel jLabel_OR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Custom;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    // End of variables declaration//GEN-END:variables

  private  void validateInput(String text, String pattern)
  {
//    Pattern r = Pattern.compile(pattern);
//    Matcher m = r.matcher(text);
//    if (!m.matches())
//    {
//      JOptionPane.showMessageDialog(SetReminderForMortAndDebt.this,"<html><b>Only Digits ! </b><br><br>Please enter only digits.</html>", "Validation", JOptionPane.WARNING_MESSAGE);
//    }
//    
  }
}
